export const DEFAULT_SETTINGS = {
  worldWidth: 96,
  worldHeight: 64,

  renderDetail: "balanced",
  showGrid: false,

  initialGrassDensity: 0.7,
  grassRegrowth: 0.42,
  grassMax: 100,
  grassBite: 28,
  grassEnergy: 1.15,

  terrainEnabled: true,
  waterAmount: 0.035,
  forestAmount: 0.11,
  barrenAmount: 0.08,
  fertileAmount: 0.09,
  riverAmount: 0.55,
  biomeScale: 24,

  environmentalEventsEnabled: true,
  environmentalEventChance: 0.00045,
  environmentalEventCooldown: 260,
  environmentalEventMinDuration: 220,
  environmentalEventMaxDuration: 650,
  maxActiveEnvironmentalEvents: 2,
  preyDiseaseMortalityChance: 0.00045,
  predatorDiseaseMortalityChance: 0.0007,
  wildfireIntensity: 0.45,

  seasonsEnabled: true,
  seasonLength: 650,

  migrationEnabled: true,
  preyMigrationChance: 0.0012,
  predatorMigrationChance: 0.00035,
  preyMigrationGroupSize: 4,
  predatorMigrationGroupSize: 2,
  predatorMigrationMinimumPrey: 45,

  initialPrey: 110,
  initialPredators: 24,

  preySpeed: 0.62,
  preyVision: 7,
  preyCaution: 0.9,
  preyMetabolism: 1,
  preyHunger: 0.42,
  preyStartEnergy: 55,
  preyReproductionEnergy: 92,
  preyReproductionCost: 38,
  preyReproductionChance: 0.034,
  preyMaxAge: 1400,
  preyRecentFoodNeeded: 6,
  preyCrowdingRadius: 3.2,
  preyCrowdingEnergyCost: 0.018,
  preyCrowdingReproductionPenalty: 0.18,

  predatorSpeed: 0.78,
  predatorVision: 10,
  predatorAggression: 1,
  predatorMetabolism: 1,
  predatorHunger: 0.68,
  predatorStartEnergy: 82,
  predatorReproductionEnergy: 135,
  predatorReproductionCost: 55,
  predatorReproductionChance: 0.022,
  predatorKillRadius: 0.85,
  predatorEatEnergy: 62,
  predatorMaxAge: 1800,
  predatorHandlingTime: 10,
  predatorPreyRatioForReproduction: 5.5,
  predatorCrowdingRadius: 4.4,
  predatorCrowdingEnergyCost: 0.035,
  predatorCrowdingReproductionPenalty: 0.22,

  preyHerdingRadius: 5.5,
  preyHerdingStrength: 0.42,
  preySeparationStrength: 0.78,
  preyShelterSeekingStrength: 1.15,
  preyStarvingEnergyRatio: 0.42,
  preyHerdingEnergyCost: 0.012,

  predatorPackRadius: 6.5,
  predatorPackCohesionStrength: 0.22,
  predatorPackSeparationStrength: 0.52,
  predatorPackHuntBonus: 0.045,
  predatorPackKillRadiusBonus: 0.035,
  predatorPackEnergyCost: 0.018,
  predatorStarvingEnergyRatio: 0.34,
  predatorRestChance: 0.58,
  predatorRestEnergySave: 0.22,

  civilizationEnabled: false,
  initialHumans: 6,
  maxHumans: 80,
  initialHumanFood: 90,
  initialHumanWood: 30,
  initialHuts: 1,
  humansPerHut: 8,
  humanSpeed: 0.52,
  humanHunger: 0.045,
  humanMaxAge: 2600,
  humanRoamRadius: 14,
  humanHuntRadius: 7,
  humanKillRadius: 0.7,
  humanHuntChance: 0.08,
  humanHuntFoodGain: 28,
  humanFoodGatherRate: 10,
  humanWoodGatherRate: 1.7,
  humanFoodConsumptionRate: 0.032,
  humanGrowthChance: 0.012,
  humanGrowthFoodThreshold: 170,
  humanGrowthFoodCost: 70,
  hutBuildChance: 0.018,
  hutBuildCooldown: 260,
  hutWoodCost: 80,
  hutFoodCost: 45,
  humanSettlementImpactRadius: 7,
  humanLandPressure: 0.34,
  humanForestDamage: 0.8,
  humanDeforestationChance: 0.00055,
  humanPassiveDeforestationChance: 0.00006,

  mutationRate: 0.08,
  traitVariance: 0.12,

  maxPrey: 700,
  maxPredators: 210,

  randomWander: 0.32,
  chartEveryTicks: 8,
  historyLimit: 260,
  seed: 2905,
};

export const MAP_SIZES = {
  compact: {
    label: "Compact",
    description: "Smaller world, faster simulation.",
    width: 72,
    height: 48,
    maxPrey: 520,
    maxPredators: 160,
    initialPrey: 75,
    initialPredators: 16,
  },
  standard: {
    label: "Standard",
    description: "Balanced world size for most experiments.",
    width: 96,
    height: 64,
    maxPrey: 900,
    maxPredators: 260,
    initialPrey: 110,
    initialPredators: 24,
  },
  large: {
    label: "Large",
    description: "More space and richer regional dynamics.",
    width: 128,
    height: 80,
    maxPrey: 1400,
    maxPredators: 380,
    initialPrey: 165,
    initialPredators: 36,
  },
  huge: {
    label: "Huge",
    description: "Big ecosystem. Best with balanced or performance rendering.",
    width: 160,
    height: 96,
    maxPrey: 2200,
    maxPredators: 560,
    initialPrey: 230,
    initialPredators: 52,
  },
};

export const RENDER_DETAILS = {
  performance: {
    label: "Performance",
    description: "Faster drawing with fewer terrain details.",
  },
  balanced: {
    label: "Balanced",
    description: "Good visuals and good performance.",
  },
  detailed: {
    label: "Detailed",
    description: "More terrain details. Best for compact or standard maps.",
  },
};

export const TRAIT_LIMITS = {
  prey: {
    speed: [0.35, 1.25],
    vision: [3, 16],
    caution: [0.1, 1.8],
    metabolism: [0.65, 1.55],
    reproductionEnergy: [55, 150],
  },
  predator: {
    speed: [0.35, 1.45],
    vision: [4, 22],
    aggression: [0.2, 2],
    metabolism: [0.65, 1.8],
    reproductionEnergy: [85, 220],
  },
};

export const PRESETS = {
  balanced: {
    label: "Balanced Meadow",
    description:
      "A balanced setup with clustered biomes, rivers and population waves.",
    settings: {},
  },

  rabbitBoom: {
    label: "Prey Boom",
    description: "Lots of prey and few predators. Watch for overgrazing.",
    settings: {
      initialPrey: 190,
      initialPredators: 8,
      grassRegrowth: 0.34,
      preyReproductionChance: 0.06,
      forestAmount: 0.07,
      barrenAmount: 0.11,
      biomeScale: 22,
    },
  },

  predatorPressure: {
    label: "Predator Pressure",
    description: "More predators. Forest pockets may help prey survive.",
    settings: {
      initialPrey: 125,
      initialPredators: 42,
      predatorHunger: 0.72,
      predatorReproductionChance: 0.024,
      forestAmount: 0.16,
      biomeScale: 26,
    },
  },

  harshWorld: {
    label: "Harsh World",
    description: "Dry regions and winter pressure make survival difficult.",
    settings: {
      initialGrassDensity: 0.52,
      grassRegrowth: 0.18,
      preyHunger: 0.52,
      predatorHunger: 0.82,
      mutationRate: 0.11,
      barrenAmount: 0.2,
      fertileAmount: 0.04,
      waterAmount: 0.025,
      riverAmount: 0.35,
      biomeScale: 30,
    },
  },

  fastEvolution: {
    label: "Fast Evolution",
    description: "Higher mutation rate makes trait changes visible faster.",
    settings: {
      mutationRate: 0.18,
      preyReproductionChance: 0.06,
      predatorReproductionChance: 0.04,
      initialPrey: 145,
      initialPredators: 28,
      forestAmount: 0.12,
      fertileAmount: 0.1,
      biomeScale: 20,
    },
  },

  longWinter: {
    label: "Long Winter",
    description:
      "Longer seasons and harsh winter pressure test survival traits.",
    settings: {
      seasonLength: 950,
      grassRegrowth: 0.35,
      initialGrassDensity: 0.62,
      preyHunger: 0.48,
      predatorHunger: 0.78,
      mutationRate: 0.12,
      forestAmount: 0.13,
      barrenAmount: 0.12,
      biomeScale: 28,
    },
  },

  forestRefuge: {
    label: "Forest Refuge",
    description:
      "Large forest regions give prey shelter and create safer zones.",
    settings: {
      forestAmount: 0.24,
      waterAmount: 0.025,
      riverAmount: 0.45,
      barrenAmount: 0.04,
      fertileAmount: 0.12,
      initialPrey: 120,
      initialPredators: 30,
      biomeScale: 30,
    },
  },

  brokenLands: {
    label: "Broken Lands",
    description:
      "Rivers, water and barren regions fragment the map into survival pockets.",
    settings: {
      waterAmount: 0.075,
      riverAmount: 0.9,
      barrenAmount: 0.18,
      fertileAmount: 0.06,
      forestAmount: 0.08,
      grassRegrowth: 0.3,
      initialPrey: 100,
      initialPredators: 20,
      biomeScale: 26,
    },
  },

  wetlands: {
    label: "Wetlands",
    description:
      "More water, fertile edges and forest clusters create rich but fragmented habitats.",
    settings: {
      waterAmount: 0.065,
      riverAmount: 0.85,
      forestAmount: 0.16,
      fertileAmount: 0.16,
      barrenAmount: 0.03,
      grassRegrowth: 0.48,
      initialPrey: 135,
      initialPredators: 24,
      biomeScale: 25,
    },
  },

  plainWorld: {
    label: "Plain World",
    description:
      "A simple open grassland with no water, rivers, forests or blocked terrain.",
    settings: {
      terrainEnabled: false,
      waterAmount: 0,
      riverAmount: 0,
      forestAmount: 0,
      barrenAmount: 0,
      fertileAmount: 0,
      biomeScale: 24,
      initialGrassDensity: 0.72,
      grassRegrowth: 0.42,
      initialPrey: 120,
      initialPredators: 24,
    },
  },

  stableEcosystem: {
    label: "Stable Ecosystem",
    description:
      "Tuned for longer coexistence, slower collapse and more visible evolution.",
    settings: {
      initialPrey: 120,
      initialPredators: 18,
      maxPrey: 650,
      maxPredators: 190,
      grassRegrowth: 0.38,
      preyHunger: 0.45,
      predatorHunger: 0.7,
      preyReproductionChance: 0.032,
      predatorReproductionChance: 0.02,
      predatorEatEnergy: 60,
      predatorHandlingTime: 12,
      predatorPreyRatioForReproduction: 6.2,
      preyCrowdingEnergyCost: 0.022,
      preyCrowdingReproductionPenalty: 0.22,
      predatorCrowdingEnergyCost: 0.04,
      predatorCrowdingReproductionPenalty: 0.26,
      mutationRate: 0.11,
      forestAmount: 0.14,
      fertileAmount: 0.1,
      barrenAmount: 0.07,
      waterAmount: 0.025,
      riverAmount: 0.45,
      biomeScale: 28,
    },
  },

  migrationCorridor: {
    label: "Migration Corridor",
    description:
      "Occasional prey and predator migration can rescue or destabilize the ecosystem.",
    settings: {
      migrationEnabled: true,
      preyMigrationChance: 0.0022,
      predatorMigrationChance: 0.00065,
      preyMigrationGroupSize: 6,
      predatorMigrationGroupSize: 2,
      predatorMigrationMinimumPrey: 55,
      initialPrey: 95,
      initialPredators: 16,
      maxPrey: 750,
      maxPredators: 210,
      forestAmount: 0.13,
      fertileAmount: 0.11,
      waterAmount: 0.025,
      riverAmount: 0.55,
      biomeScale: 30,
      mutationRate: 0.12,
    },
  },

  volatileWorld: {
    label: "Volatile World",
    description:
      "Frequent droughts, blooms, disease and wildfire create a turbulent ecosystem.",
    settings: {
      environmentalEventsEnabled: true,
      environmentalEventChance: 0.0012,
      environmentalEventCooldown: 160,
      environmentalEventMinDuration: 160,
      environmentalEventMaxDuration: 520,
      maxActiveEnvironmentalEvents: 2,
      migrationEnabled: true,
      preyMigrationChance: 0.0018,
      predatorMigrationChance: 0.00055,
      initialPrey: 120,
      initialPredators: 20,
      maxPrey: 700,
      maxPredators: 210,
      grassRegrowth: 0.42,
      mutationRate: 0.13,
      forestAmount: 0.14,
      fertileAmount: 0.12,
      barrenAmount: 0.08,
      waterAmount: 0.03,
      riverAmount: 0.6,
      biomeScale: 28,
    },
  },

  behaviorLab: {
    label: "Behavior Lab",
    description:
      "Stronger herding, shelter seeking and pack pressure make species behavior more visible.",
    settings: {
      initialPrey: 130,
      initialPredators: 22,
      maxPrey: 760,
      maxPredators: 220,
      preyHerdingStrength: 0.68,
      preySeparationStrength: 0.95,
      preyShelterSeekingStrength: 1.55,
      predatorPackCohesionStrength: 0.36,
      predatorPackHuntBonus: 0.07,
      predatorPackKillRadiusBonus: 0.05,
      predatorRestChance: 0.68,
      forestAmount: 0.18,
      fertileAmount: 0.11,
      barrenAmount: 0.06,
      waterAmount: 0.025,
      riverAmount: 0.5,
      migrationEnabled: true,
      preyMigrationChance: 0.0015,
      predatorMigrationChance: 0.00045,
      mutationRate: 0.12,
      biomeScale: 28,
    },
  },

  civilizationFrontier: {
    label: "Civilization Frontier",
    description:
      "A small human settlement gathers resources, hunts prey and slowly changes the ecosystem.",
    settings: {
      civilizationEnabled: true,
      initialHumans: 7,
      maxHumans: 70,
      initialHumanFood: 110,
      initialHumanWood: 45,
      initialHuts: 1,
      initialPrey: 150,
      initialPredators: 18,
      maxPrey: 850,
      maxPredators: 210,
      forestAmount: 0.2,
      fertileAmount: 0.14,
      barrenAmount: 0.06,
      waterAmount: 0.03,
      riverAmount: 0.55,
      biomeScale: 30,
      migrationEnabled: true,
      environmentalEventsEnabled: true,
      environmentalEventChance: 0.00055,
      mutationRate: 0.12,
    },
  },

  recoveryLab: {
    label: "Recovery Lab",
    description: "Few predators, damaged grass, and a fragile recovery curve.",
    settings: {
      initialGrassDensity: 0.34,
      grassRegrowth: 0.5,
      initialPrey: 70,
      initialPredators: 4,
      fertileAmount: 0.12,
      barrenAmount: 0.14,
      riverAmount: 0.4,
      biomeScale: 22,
    },
  },
};

export function getPresetSettings(presetKey) {
  const preset = PRESETS[presetKey] ?? PRESETS.balanced;

  return {
    ...DEFAULT_SETTINGS,
    ...preset.settings,
  };
}
