export const DEFAULT_SETTINGS = {
  worldWidth: 96,
  worldHeight: 64,

  renderDetail: "balanced",
  showGrid: false,

  initialGrassDensity: 0.7,
  grassRegrowth: 0.42,
  grassMax: 100,
  grassBite: 28,
  grassEnergy: 1.15,

  terrainEnabled: true,
  waterAmount: 0.035,
  forestAmount: 0.11,
  barrenAmount: 0.08,
  fertileAmount: 0.09,
  riverAmount: 0.55,
  biomeScale: 24,

  environmentalEventsEnabled: true,
  environmentalEventChance: 0.00045,
  environmentalEventCooldown: 260,
  environmentalEventMinDuration: 220,
  environmentalEventMaxDuration: 650,
  maxActiveEnvironmentalEvents: 2,
  preyDiseaseMortalityChance: 0.00045,
  predatorDiseaseMortalityChance: 0.0007,
  wildfireIntensity: 0.45,

  seasonsEnabled: true,
  seasonLength: 650,

  migrationEnabled: true,
  preyMigrationChance: 0.0012,
  predatorMigrationChance: 0.00035,
  preyMigrationGroupSize: 4,
  predatorMigrationGroupSize: 2,
  predatorMigrationMinimumPrey: 45,

  initialPrey: 110,
  initialPredators: 24,

  preySpeed: 0.62,
  preyVision: 7,
  preyCaution: 0.9,
  preyMetabolism: 1,
  preyHunger: 0.42,
  preyStartEnergy: 55,
  preyReproductionEnergy: 92,
  preyReproductionCost: 38,
  preyReproductionChance: 0.029,
  preyMaxAge: 1400,
  preyRecentFoodNeeded: 6,
  preyCrowdingRadius: 3.2,
  preyCrowdingEnergyCost: 0.018,
  preyCrowdingReproductionPenalty: 0.18,

  predatorSpeed: 0.78,
  predatorVision: 10,
  predatorAggression: 1,
  predatorMetabolism: 1,
  predatorHunger: 0.68,
  predatorStartEnergy: 82,
  predatorReproductionEnergy: 135,
  predatorReproductionCost: 55,
  predatorReproductionChance: 0.019,
  predatorKillRadius: 0.85,
  predatorEatEnergy: 62,
  predatorMaxAge: 1800,
  predatorHandlingTime: 10,
  predatorPreyRatioForReproduction: 5.5,
  predatorCrowdingRadius: 4.4,
  predatorCrowdingEnergyCost: 0.035,
  predatorCrowdingReproductionPenalty: 0.22,

  preyHerdingRadius: 5.5,
  preyHerdingStrength: 0.42,
  preySeparationStrength: 0.78,
  preyShelterSeekingStrength: 1.15,
  preyStarvingEnergyRatio: 0.42,
  preyHerdingEnergyCost: 0.012,

  preyCarryingPressureStrength: 0.72,
  preyGrassScarcityPressure: 0.95,
  preyOverpopulationMortality: 0.00115,
  preyReproductionGrassRequirement: 0.26,

  predatorOverpopulationMortality: 0.00045,
  predatorPreyScarcityPressure: 0.48,

  predatorPackRadius: 6.5,
  predatorPackCohesionStrength: 0.22,
  predatorPackSeparationStrength: 0.52,
  predatorPackHuntBonus: 0.045,
  predatorPackKillRadiusBonus: 0.035,
  predatorPackEnergyCost: 0.018,
  predatorStarvingEnergyRatio: 0.34,
  predatorRestChance: 0.58,
  predatorRestEnergySave: 0.22,

  civilizationEnabled: false,
  initialHumans: 6,
  maxHumans: 80,
  initialHumanFood: 90,
  initialHumanWood: 30,
  initialHuts: 1,
  humansPerHut: 8,
  humanSpeed: 0.52,
  humanHunger: 0.045,
  humanMaxAge: 2600,
  humanRoamRadius: 14,
  humanHuntRadius: 7,
  humanKillRadius: 0.7,
  humanHuntChance: 0.035,
  humanHuntFoodGain: 28,
  humanFoodGatherRate: 10,
  humanWoodGatherRate: 1.7,
  humanFoodConsumptionRate: 0.028,
  humanGrowthChance: 0.007,
  humanGrowthFoodThreshold: 170,
  humanGrowthFoodCost: 70,
  hutBuildChance: 0.018,
  hutBuildCooldown: 260,
  hutWoodCost: 80,
  hutFoodCost: 45,
  humanSettlementImpactRadius: 7,
  humanLandPressure: 0.2,
  humanForestDamage: 0.8,
  humanDeforestationChance: 0.00024,
  humanPassiveDeforestationChance: 0.000025,
  humanMinimumPreyBeforeHunting: 95,

  bridgeBuildingEnabled: true,
  bridgeBuildStartTick: 1100,
  bridgeBuildChance: 0.009,
  bridgeBuildCooldown: 1100,
  bridgeWoodCost: 110,
  bridgeFoodCost: 40,
  bridgeSearchRadius: 22,
  bridgeMinimumSpacing: 18,
  bridgeMovementBonus: 1.1,

  roadBuildingEnabled: true,
  roadCreateChance: 0.032,
  roadWearGain: 0.026,
  roadInitialStrength: 0.18,
  roadMinimumStrength: 0.04,
  roadActiveDecay: 0.00008,
  roadUnusedDecay: 0.00055,
  roadRecentUseWindow: 500,
  roadMaxDistanceFromSettlement: 26,
  maxRoadCells: 320,
  roadMovementBonus: 1.06,

  mutationRate: 0.08,
  traitVariance: 0.12,

  maxPrey: 680,
  maxPredators: 205,

  randomWander: 0.32,
  chartEveryTicks: 8,
  historyLimit: 260,
  seed: 2905,
};

export const MAP_SIZES = {
  compact: {
    label: "Compact",
    description: "Smaller world, faster simulation.",
    width: 72,
    height: 48,
    maxPrey: 520,
    maxPredators: 160,
    initialPrey: 75,
    initialPredators: 16,
  },
  standard: {
    label: "Standard",
    description: "Balanced world size for most experiments.",
    width: 96,
    height: 64,
    maxPrey: 680,
    maxPredators: 205,
    initialPrey: 110,
    initialPredators: 24,
  },
  large: {
    label: "Large",
    description: "More space and richer regional dynamics.",
    width: 128,
    height: 80,
    maxPrey: 1200,
    maxPredators: 340,
    initialPrey: 155,
    initialPredators: 34,
  },
  huge: {
    label: "Huge",
    description: "Big ecosystem. Best with balanced or performance rendering.",
    width: 160,
    height: 96,
    maxPrey: 1800,
    maxPredators: 480,
    initialPrey: 220,
    initialPredators: 48,
  },
};

export const RENDER_DETAILS = {
  performance: {
    label: "Performance",
    description: "Faster drawing with fewer terrain details.",
  },
  balanced: {
    label: "Balanced",
    description: "Good visuals and good performance.",
  },
  detailed: {
    label: "Detailed",
    description: "More terrain details. Best for compact or standard maps.",
  },
};

export const TRAIT_LIMITS = {
  prey: {
    speed: [0.35, 1.25],
    vision: [3, 16],
    caution: [0.1, 1.8],
    metabolism: [0.65, 1.55],
    reproductionEnergy: [55, 150],
  },
  predator: {
    speed: [0.35, 1.45],
    vision: [4, 22],
    aggression: [0.2, 2],
    metabolism: [0.65, 1.8],
    reproductionEnergy: [85, 220],
  },
};

export const PRESETS = {
  balanced: {
    label: "Balanced Meadow",
    description:
      "Default ecosystem with terrain, seasons, migration and balanced predator-prey pressure.",
    settings: {},
  },

  stableEcosystem: {
    label: "Stable Ecosystem",
    description:
      "Tuned for longer coexistence, slower collapse and more visible evolution.",
    settings: {
      initialPrey: 115,
      initialPredators: 17,
      maxPrey: 620,
      maxPredators: 180,
      grassRegrowth: 0.4,
      preyHunger: 0.46,
      predatorHunger: 0.69,
      preyReproductionChance: 0.028,
      predatorReproductionChance: 0.018,
      predatorEatEnergy: 58,
      predatorHandlingTime: 13,
      predatorPreyRatioForReproduction: 6.5,
      preyCrowdingEnergyCost: 0.024,
      preyCrowdingReproductionPenalty: 0.25,
      preyCarryingPressureStrength: 0.82,
      preyGrassScarcityPressure: 1.05,
      preyOverpopulationMortality: 0.0012,
      preyReproductionGrassRequirement: 0.28,
      predatorCrowdingEnergyCost: 0.04,
      predatorCrowdingReproductionPenalty: 0.28,
      predatorPreyScarcityPressure: 0.5,
      mutationRate: 0.11,
      forestAmount: 0.15,
      fertileAmount: 0.11,
      barrenAmount: 0.07,
      waterAmount: 0.025,
      riverAmount: 0.45,
      biomeScale: 30,
    },
  },

  plainWorld: {
    label: "Plain World",
    description:
      "Open grassland with no terrain barriers. Good for testing pure population balance.",
    settings: {
      terrainEnabled: false,
      waterAmount: 0,
      riverAmount: 0,
      forestAmount: 0,
      barrenAmount: 0,
      fertileAmount: 0,
      biomeScale: 24,
      initialGrassDensity: 0.72,
      grassRegrowth: 0.38,
      initialPrey: 105,
      initialPredators: 22,
      maxPrey: 560,
      maxPredators: 170,
      preyReproductionChance: 0.027,
      predatorReproductionChance: 0.02,
      preyCarryingPressureStrength: 0.95,
      preyGrassScarcityPressure: 1.15,
      preyOverpopulationMortality: 0.0015,
      preyReproductionGrassRequirement: 0.3,
      migrationEnabled: true,
      preyMigrationChance: 0.0008,
      predatorMigrationChance: 0.00035,
      environmentalEventsEnabled: false,
    },
  },

  continentalWilds: {
    label: "Continental Wilds",
    description:
      "Large natural regions, stronger rivers and richer biome structure.",
    settings: {
      waterAmount: 0.045,
      riverAmount: 0.75,
      forestAmount: 0.17,
      fertileAmount: 0.13,
      barrenAmount: 0.08,
      biomeScale: 36,
      initialPrey: 140,
      initialPredators: 24,
      maxPrey: 900,
      maxPredators: 240,
      migrationEnabled: true,
      environmentalEventsEnabled: true,
      mutationRate: 0.11,
    },
  },

  volatileWorld: {
    label: "Volatile World",
    description:
      "Frequent droughts, blooms, disease and wildfire create a turbulent ecosystem.",
    settings: {
      environmentalEventsEnabled: true,
      environmentalEventChance: 0.0012,
      environmentalEventCooldown: 160,
      environmentalEventMinDuration: 160,
      environmentalEventMaxDuration: 520,
      maxActiveEnvironmentalEvents: 2,
      migrationEnabled: true,
      preyMigrationChance: 0.0018,
      predatorMigrationChance: 0.00055,
      initialPrey: 120,
      initialPredators: 20,
      maxPrey: 700,
      maxPredators: 210,
      grassRegrowth: 0.42,
      mutationRate: 0.13,
      forestAmount: 0.14,
      fertileAmount: 0.12,
      barrenAmount: 0.08,
      waterAmount: 0.03,
      riverAmount: 0.6,
      biomeScale: 28,
    },
  },

  behaviorLab: {
    label: "Behavior Lab",
    description:
      "Stronger herding, shelter seeking and pack pressure make species behavior more visible.",
    settings: {
      initialPrey: 130,
      initialPredators: 22,
      maxPrey: 760,
      maxPredators: 220,
      preyHerdingStrength: 0.68,
      preySeparationStrength: 0.95,
      preyShelterSeekingStrength: 1.55,
      predatorPackCohesionStrength: 0.36,
      predatorPackHuntBonus: 0.07,
      predatorPackKillRadiusBonus: 0.05,
      predatorRestChance: 0.68,
      forestAmount: 0.18,
      fertileAmount: 0.11,
      barrenAmount: 0.06,
      waterAmount: 0.025,
      riverAmount: 0.5,
      migrationEnabled: true,
      preyMigrationChance: 0.0015,
      predatorMigrationChance: 0.00045,
      mutationRate: 0.12,
      biomeScale: 28,
    },
  },

  recoveryLab: {
    label: "Recovery Lab",
    description:
      "Damaged grass and low populations create a fragile recovery experiment.",
    settings: {
      initialGrassDensity: 0.34,
      grassRegrowth: 0.5,
      initialPrey: 70,
      initialPredators: 4,
      maxPrey: 520,
      maxPredators: 130,
      fertileAmount: 0.12,
      barrenAmount: 0.14,
      riverAmount: 0.4,
      biomeScale: 22,
      migrationEnabled: true,
      preyMigrationChance: 0.0016,
      predatorMigrationChance: 0.00025,
      environmentalEventsEnabled: false,
    },
  },
};

export function getPresetSettings(presetKey) {
  const preset = PRESETS[presetKey] ?? PRESETS.balanced;

  return {
    ...DEFAULT_SETTINGS,
    ...preset.settings,
    civilizationEnabled: false,
  };
}
